apiVersion: v1
kind: Service
metadata:
  name: fiap-lanches-loadbalance-svc
spec:
  selector:
    app: fiap-lanches-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer