apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/postgres/minikube/storage/data/"
    type: DirectoryOrCreate
  