apiVersion: v1
kind: Pod
metadata:
  name: teste-conexao-postgres
spec:
  containers:
    - name: teste-conexao-postgres
      image: alpine:latest
      command: ["sh", "-c"]
      args:
        - |
          apk update
          apk add postgresql-client
          PGPASSWORD=admin123 psql -h postgres -U admin -d fiaplanches -c "SELECT 1;" && echo "Conexão bem-sucedida com o banco de dados" || echo "Erro na conexão com o banco de dados"
      env:
        - name: postgres
          value: postgres  # Substitua pelo nome do seu serviço PostgreSQL
        - name: admin
          value: admin  # Substitua pelo nome do usuário do PostgreSQL
        - name: fiaplanches
          value: fiaplanches  # Substitua pelo nome do banco de dados PostgreSQL
  restartPolicy: Never
  